### ISSUE TITLE
QuestionOptions na tela de criação de teste no admin

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern-app#29]
**Rota**: admin/provas/novo
- problema é que o componente de remoção está como children de um `RadioButton` na view `PublicContentCreateQuestionCreateAnswer`
```javascript
<RadioButtonGroup
              onChange={this.handleAnswerChange}
              name='options'
              defaultSelected='not_light'>
              {_.map(form.doc.get('options'), (c, i) =>
                    <RadioButton
                      value={i}
                      key={i}
                      label={<PublicContentShow
                        field='options'
                        schema={Tests.PageContentSchema}
                        index={i}
                        form={form}
                        doc={c} />} />)}
            </RadioButtonGroup>
```

**Comment by deleuterio** [comment]
Alinhar na view `PublicContentShowQuestionView`:
![selection_005](https://cloud.githubusercontent.com/assets/12951402/23232445/09261b36-f92a-11e6-99d0-82e909a28472.png)

**Comment by andredornas** [comment]
RadioButtonGroup não aceita um nested <div>

[](https://github.com/callemall/material-ui/issues/2225)

**Comment by andredornas** [comment]
RadioButtonGroup não aceita um nested `<div>`

https://github.com/callemall/material-ui/issues/2225

**Comment by andredornas** [comment]
@deleuterio não está obrigatório selecionar uma resposta para uma questão fechada, acho que é por causa do modelo e do astronomy

**Comment by deleuterio** [comment]
Só fechar essa bagaça :smile:
