### ISSUE TITLE
Alterar card de exibição de atividades para material design

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern-app#65]
Nesse card deve ter apenas um botão que vai encaminhar para uma tela que será uma espécie de overview do teste, que além de deixar fazer o teste, terá também um botão para ver tentativas e por fim vai exibir as informações do teste logo após o cabeçalho da tela. Usar a home do course show como exemplo.

**Comment by dantenol** [comment]
desabilitar aba de atividades se tiver apenas uma, assim como aba de aula se nao tiver aula

**Comment by deleuterio** [comment]
Terminei num commit avulso
https://github.com/lern-edu/lern-app/commit/87184222f38e8926dac48ad38e8a3d287dcf0404
